[tool.poetry.dependencies]
python = ">=3.11"

fastapi = "*"
uvicorn = "*"
motor = "*"
pymongo = "*"
certifi = "*"

bcrypt = "3.2.2"
passlib = { extras = ["bcrypt"], version = ">=1.7.4" }

python-jose = { extras = ["cryptography"], version = "*" }
python-dotenv = "*"
groq = "*"
pydantic = { extras = ["email"], version = "*" }